language: node_js
cache:
  directories:
  - node_modules
node_js:
- '9'
- '8'
- '6'
after_success:
- npm run coverall
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_KEY
  on:
    tags: true
    repo: adam-mccormick/moleculer-axios
